version: 2

jobs:
  build:
    docker:
      # Has C++ too
      - image: circleci/rust:1.39
    working_directory: ~/pm_sensor
    steps:
      - checkout
      - run:
          name: run apt-get update
          command: sudo apt-get update
      - run:
          name: install packages
          command: sudo apt-get install -y ninja-build python3-pip
      - restore_cache:
          name: Restore pip cache
          keys:
            - v2-pm_sensor-pip
      - run:
          pip3 install --user meson
      - save_cache:
          name: Save pip cache
          key: v2-pm_sensor-pip
          paths:
            - ~/.local/lib/python3.5/site-packages/
            - ~/.cache/pip/
      - restore_cache:
          name: Restore meson subprojects cache
          keys:
            - v1-pm_sensor-meson-packagecache-{{ checksum "meson.build" }}
            - v1-pm_sensor-meson-packagecache-
      - run:
          command: /home/circleci/.local/bin/meson builddir
      - save_cache:
          name: Save meson subprojects cache
          key: v1-pm_sensor-meson-packagecache-{{ checksum "meson.build" }}
          paths:
            - ~/pm_sensor/subprojects/packagecache
      - run:
          command: ninja test
          working_directory: ~/pm_sensor/builddir
      - store_artifacts:
          path: /home/circleci/pm_sensor/builddir/meson-logs
          destination: meson-logs

      - restore_cache:
          name: Restore cargo cache
          key: v1-pm_sensor-cargo
      - run:
          name: Build logging_node
          working_directory: ~/pm_sensor/logging_node
          command: cargo build
      - run:
          name: Test logging_node
          working_directory: ~/pm_sensor/logging_node
          command: cargo test
      - save_cache:
          name: Save cargo cache
          key: v1-pm_sensor-cargo
          paths:
            - "~/.cargo"
            - "~/pm_sensor/logging_node/target"
